# Generated by Django 4.2.19 on 2025-12-01 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S3AssetMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_str', models.CharField(db_index=True, help_text="String representation of the asset's location (AssetKey)", max_length=255, unique=True)),
                ('course_key_str', models.CharField(db_index=True, help_text='String representation of the course key', max_length=255)),
                ('s3_key', models.CharField(db_index=True, help_text='S3 object key where the file is stored', max_length=255)),
                ('asset_name', models.CharField(default='', help_text='Display name of the asset', max_length=255)),
                ('content_type', models.CharField(default='application/octet-stream', help_text='MIME type of the asset', max_length=255)),
                ('content_digest', models.CharField(blank=True, default='', help_text='MD5 hash of the file content', max_length=64)),
                ('length', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('thumbnail_location', models.CharField(blank=True, help_text='String representation of the thumbnail location', max_length=255, null=True)),
                ('import_path', models.CharField(blank=True, default='', help_text='Original import path from course archive', max_length=255)),
                ('locked', models.BooleanField(default=False, help_text='Whether the asset is locked')),
                ('custom_metadata', models.JSONField(blank=True, help_text='Additional custom metadata as JSON', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the asset was first uploaded')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the asset was last modified')),
            ],
            options={
                'verbose_name': 'S3 Asset Metadata',
                'verbose_name_plural': 'S3 Asset Metadata',
                'db_table': 's3_contentstore_asset_metadata',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course_key_str', 'created_at'], name='s3_contents_course__bbd039_idx'), models.Index(fields=['course_key_str', 'asset_name'], name='s3_contents_course__04b4a1_idx'), models.Index(fields=['content_type'], name='s3_contents_content_bbb5f7_idx')],
            },
        ),
    ]
